### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by samuelogboye** [div-styl/connect#2]
Thanks so much for this beautiful concept. I'm working on refactoring this code, you'll get a PR now. Kindly go through it

thanks

**Comment by Abdogouhmad** [comment]
> Thanks so much for this beautiful concept. I'm working on refactoring this code, you'll get a PR now. Kindly go through it
> 
> thanks

so excited to see what are you going to make

**Comment by samuelogboye** [comment]
I'm done boss, kindly check the PR
